- name: Update Operating Systems
  hosts: all
  become: True

  tasks:
    - name: Update Cache Packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade Packages
      apt:
        name: "*"
        state: latest

    - name: Execute Autoremove
      apt:
        autoremove: yes

  vars:
    ansible_user: pi
    ansible_private_key_file: ~/.ssh/ssh-cluster
    ansible_port: 22

# Default Raspbian User: pi
# Default Raspbian Password: raspbian
# Default Raspbian Config: sudoers.d NOPASSWD
